export const ErrorCodeEnum = {
    // Common Errors
    AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
    AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
    AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",

    // Auth Errors
    AUTH_NOT_FOUND: "AUTH_NOT_FOUND",
    AUTH_TOO_MANY_REQUESTS: "AUTH_TOO_MANY_REQUESTS",
    AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
    AUTH_TOKEN_NOT_FOUND: "AUTH_TOKEN_NOT_FOUND",

    // Access Control Errors
    ACCESS_UNAUTHORIZED: "ACCESS_UNAUTHORIZED",

    // Validation Errors
    VALIDATION_ERROR: "VALIDATION_ERROR",
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

    // Internal Server Errors
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCodeEnumType = keyof typeof ErrorCodeEnum;
